export interface Video {
  id: string
  title: string
  thumbnail: string
  tags: string[]
  uploadDate: string
  duration: string
  videoId: string
  description?: string
}

export const videosByYear: Record<string, Video[]> = {
  "2025": [
    {
      id: "1",
      title: "お友達大作戦",
      thumbnail: "https://img.youtube.com/vi/FSu7hLBcNj8/hqdefault.jpg",
      tags: ["BO6", "LoL", "VALORANT"],
      uploadDate: "2025-01-01",
      duration: "1:45",
      videoId: "FSu7hLBcNj8",
      description: "BO6、LoL、VALORANTで友達と連携プレイを楽しんだ動画です。",
    },
    {
      id: "2",
      title: "邪魔です",
      thumbnail: "https://img.youtube.com/vi/B30hqhUyDH4/maxresdefault.jpg",
      tags: ["VALORANT", "ApexLegends"],
      uploadDate: "2025-02-01",
      duration: "5:20",
      videoId: "B30hqhUyDH4",
      description: "VALORANTとApex Legendsでの面白いハプニングシーンをまとめました。",
    },
    {
      id: "3",
      title: "この注文ギブでw",
      thumbnail: "https://img.youtube.com/vi/80zCbY6ztZc/hqdefault.jpg",
      tags: ["OverCooked2", "VALORANT", "LethalCompany"],
      uploadDate: "2025-03-01",
      duration: "5:41",
      videoId: "80zCbY6ztZc",
      description: "OverCooked2、VALORANT、Lethal Companyでのチームワークが試される場面を収録。",
    },
    {
      id: "4",
      title: "確キル",
      thumbnail: "https://img.youtube.com/vi/I83TiV4VnuI/maxresdefault.jpg",
      tags: ["VALORANT", "Minecraft", "CS2"],
      uploadDate: "2025-04-01",
      duration: "1:54",
      videoId: "I83TiV4VnuI",
      description: "VALORANT、Minecraft、CS2で確実にキルを取れた瞬間をまとめた動画です。",
    },
    {
      id: "5",
      title: "ヴァロクエスト",
      thumbnail: "https://img.youtube.com/vi/TymOgCmrEa0/maxresdefault.jpg",
      tags: ["VALORANT"],
      uploadDate: "2025-05-01",
      duration: "2:56",
      videoId: "TymOgCmrEa0",
      description: "VALORANTをRPG風に楽しんでプレイした企画動画です。",
    },
    {
      id: "6",
      title: "お前に背中預けるわ",
      thumbnail: "https://img.youtube.com/vi/pki-fQkTSTw/maxresdefault.jpg",
      tags: ["VALORANT", "LoL", "CS2"],
      uploadDate: "2025-06-01",
      duration: "7:57",
      videoId: "pki-fQkTSTw",
      description: "VALORANT、LoL、CS2でチームメイトとの連携プレイを楽しんだ動画。",
    },
    {
      id: "7",
      title: "まだ負けてねぇから！！！",
      thumbnail: "https://img.youtube.com/vi/cQHQSw4rN8E/maxresdefault.jpg",
      tags: ["LoL","Sea Of Thieves","omegaStrikers","VALORANT"],
      uploadDate: "2025-07-01",
      duration: "3:03",
      videoId: "cQHQSw4rN8E",
      description: "誰か全盛期集いっしょにつくろう",
    },
    {
      id: "8",
      title: "2025年8月の動画",
      thumbnail: "/placeholder.svg?height=180&width=320",
      tags: ["近日公開"],
      uploadDate: "2025-08-01",
      duration: "00:00",
      videoId: "",
      description: "近日公開予定の動画です。お楽しみに！",
    },
    {
      id: "9",
      title: "2025年9月の動画",
      thumbnail: "/placeholder.svg?height=180&width=320",
      tags: ["近日公開"],
      uploadDate: "2025-09-01",
      duration: "00:00",
      videoId: "",
      description: "近日公開予定の動画です。お楽しみに！",
    },
    {
      id: "10",
      title: "2025年10月の動画",
      thumbnail: "/placeholder.svg?height=180&width=320",
      tags: ["近日公開"],
      uploadDate: "2025-10-01",
      duration: "00:00",
      videoId: "",
      description: "近日公開予定の動画です。お楽しみに！",
    },
    {
      id: "11",
      title: "2025年11月の動画",
      thumbnail: "/placeholder.svg?height=180&width=320",
      tags: ["近日公開"],
      uploadDate: "2025-11-01",
      duration: "00:00",
      videoId: "",
      description: "近日公開予定の動画です。お楽しみに！",
    },
    {
      id: "12",
      title: "2025年12月の動画",
      thumbnail: "/placeholder.svg?height=180&width=320",
      tags: ["近日公開"],
      uploadDate: "2025-12-01",
      duration: "00:00",
      videoId: "",
      description: "近日公開予定の動画です。お楽しみに！",
    },
  ],
  "2024": [
    {
      id: "13",
      title: "キャラクリがヨボヨボのジジイなやつ",
      thumbnail: "https://img.youtube.com/vi/A1ZA22x44Og/hqdefault.jpg",
      tags: ["SF6", "overwatch2", "VALORANT", "LoL", "Minecraft"],
      uploadDate: "2024-01-01",
      duration: "3:46",
      videoId: "A1ZA22x44Og",
      description: "SF6やその他のゲームで面白いキャラクター作成を楽しんだ動画です。",
    },
    {
      id: "14",
      title: "プリクラ再び",
      thumbnail: "https://img.youtube.com/vi/oGvKj2fdQ7o/maxresdefault.jpg",
      tags: ["SF6", "HonkaiStarRail", "VALORANT", "LoL", "Minecraft"],
      uploadDate: "2024-02-01",
      duration: "8:27",
      videoId: "oGvKj2fdQ7o",
      description: "複数のゲームをプレイしながらプリクラ企画の第二弾を実施しました。",
    },
    {
      id: "15",
      title: "ごめんね♡",
      thumbnail: "https://img.youtube.com/vi/xTqCD1rhDVE/hqdefault.jpg",
      tags: ["SF6", "HonkaiStarRail", "VALORANT"],
      uploadDate: "2024-03-01",
      duration: "2:32",
      videoId: "xTqCD1rhDVE",
      description: "SF6、Honkai Star Rail、VALORANTでの謝罪シーンをまとめた動画。",
    },
    {
      id: "16",
      title: "バズりにいくぞ！",
      thumbnail: "https://img.youtube.com/vi/uso_SX6QoHM/hqdefault.jpg",
      tags: ["contentWarning", "LoL", "Minecraft", "VALORANT"],
      uploadDate: "2024-04-01",
      duration: "2:48",
      videoId: "uso_SX6QoHM",
      description: "Content Warning、LoL、Minecraft、VALORANTでバズを狙った企画動画。",
    },
    {
      id: "17",
      title: "【必見】目標4%で交代時に取るべき行動1選",
      thumbnail: "https://img.youtube.com/vi/YnNChNK2-40/hqdefault.jpg",
      tags: ["Xdefiant", "SF6", "LoL", "VALORANT"],
      uploadDate: "2024-05-01",
      duration: "9:24",
      videoId: "YnNChNK2-40",
      description: "Xdefiant、SF6、LoL、VALORANTでの攻略・解説動画です。",
    },
    {
      id: "18",
      title: "人間ラジコン",
      thumbnail: "https://img.youtube.com/vi/DiEdYdGia6s/hqdefault.jpg",
      tags: ["LethalCompany", "HonkaiStarRail"],
      uploadDate: "2024-06-01",
      duration: "2:02",
      videoId: "DiEdYdGia6s",
      description: "Lethal CompanyとHonkai Star Railで友達に操作されながらプレイした企画。",
    },
    {
      id: "19",
      title: "3Dメガネを通さないと見えないタイプの4体",
      thumbnail: "https://img.youtube.com/vi/FElO3vWfKjI/hqdefault.jpg",
      tags: ["LethalCompany", "DaD", "LoL", "VALORANT", "ZZZ"],
      uploadDate: "2024-07-01",
      duration: "4:56",
      videoId: "FElO3vWfKjI",
      description: "Lethal Company、DaD、LoL、VALORANT、ZZZでのホラー体験動画。",
    },
    {
      id: "20",
      title: "ボットのガレンを放置した結果",
      thumbnail: "https://img.youtube.com/vi/kFFhmkPerx8/hqdefault.jpg",
      tags: ["DaD", "LoL", "VALORANT"],
      uploadDate: "2024-08-01",
      duration: "3:26",
      videoId: "kFFhmkPerx8",
      description: "DaD、LoL、VALORANTでボットを放置した実験動画です。",
    },
    {
      id: "21",
      title: "1v5ドラゴンスティールの結果とは",
      thumbnail: "https://img.youtube.com/vi/f_HzPUI0vfM/hqdefault.jpg",
      tags: ["LoL", "Minecraft", "VALORANT"],
      uploadDate: "2024-09-01",
      duration: "3:20",
      videoId: "f_HzPUI0vfM",
      description: "LoL、Minecraft、VALORANTで無謀な挑戦をした結果をまとめました。",
    },
    {
      id: "22",
      title: "相手のスコアきれいだね",
      thumbnail: "https://img.youtube.com/vi/uRUKBjOq9vs/hqdefault.jpg",
      tags: ["VALORANT", "LoL", "DetroitBecameHuman", "SF6", "CS2"],
      uploadDate: "2024-10-01",
      duration: "2:53",
      videoId: "uRUKBjOq9vs",
      description: "VALORANT、LoL、Detroit Became Human、SF6、CS2での印象的なスコアシーン。",
    },
    {
      id: "23",
      title: "モンスターハンター",
      thumbnail: "https://img.youtube.com/vi/q1przkIF8O0/hqdefault.jpg",
      tags: ["VALORANT", "LoL", "overwatch2"],
      uploadDate: "2024-11-01",
      duration: "2:28",
      videoId: "q1przkIF8O0",
      description: "VALORANT、LoL、Overwatch2をモンハン風にプレイした企画動画。",
    },
    {
      id: "24",
      title: "おつり一千万円事件",
      thumbnail: "https://img.youtube.com/vi/6zJUtaLAAzU/hqdefault.jpg",
      tags: ["VALORANT", "LoL", "CS2", "superMarketTogether", "rocketLeague"],
      uploadDate: "2024-12-01",
      duration: "2:36",
      videoId: "6zJUtaLAAzU",
      description: "VALORANT、LoL、CS2、Super Market Together、Rocket Leagueでの面白事件。",
    },
  ],
  "2023": [
    {
      id: "25",
      title: "swimming chicken",
      thumbnail: "https://img.youtube.com/vi/eyxZoBk9rJo/hqdefault.jpg",
      tags: ["Minecraft", "overwatch2", "VALORANT"],
      uploadDate: "2023-01-01",
      duration: "8:58",
      videoId: "eyxZoBk9rJo",
      description: "Minecraft、Overwatch2、VALORANTでの2023年最初の動画です。",
    },
    {
      id: "26",
      title: "なにこれ広場",
      thumbnail: "https://img.youtube.com/vi/pSnIcTtA_w8/hqdefault.jpg",
      tags: ["Fallguys", "VALORANT"],
      uploadDate: "2023-02-01",
      duration: "2:57",
      videoId: "pSnIcTtA_w8",
      description: "Fall GuysとVALORANTをプレイした2月の動画。",
    },
    {
      id: "27",
      title: "ゴミパーティー９",
      thumbnail: "https://img.youtube.com/vi/qNyrQlOEjyQ/hqdefault.jpg",
      tags: ["VALORANT", "Minecraft"],
      uploadDate: "2023-03-01",
      duration: "4:38",
      videoId: "qNyrQlOEjyQ",
      description: "VALORANTとMinecraftでの春の企画動画です。",
    },
    {
      id: "28",
      title: "あなたは車庫です！",
      thumbnail: "https://img.youtube.com/vi/oVoZF-w4ODM/hqdefault.jpg",
      tags: ["omegaStrikers", "overwatch2", "VALORANT"],
      uploadDate: "2023-04-01",
      duration: "6:46",
      videoId: "oVoZF-w4ODM",
      description: "Omega Strikers、Overwatch2、VALORANTでの新学期動画。",
    },
    {
      id: "29",
      title: "オメストもんたげ",
      thumbnail: "https://img.youtube.com/vi/ap_pI5WyM8Y/maxresdefault.jpg",
      tags: ["omegaStrikers"],
      uploadDate: "2023-05-01",
      duration: "3:39",
      videoId: "ap_pI5WyM8Y",
      description: "Omega StrikersのGW期間中のプレイ動画です。",
    },
    {
      id: "30",
      title: "ヴぁぉｓｔりけｒｓ",
      thumbnail: "https://img.youtube.com/vi/P9_kNcuDS8g/hqdefault.jpg",
      tags: ["VALORANT", "omegaStrikers", "HonkaiStarRail"],
      uploadDate: "2023-06-01",
      duration: "2:17",
      videoId: "P9_kNcuDS8g",
      description: "VALORANT、Omega Strikers、Honkai Star Railでの梅雨時期の動画。",
    },
    {
      id: "31",
      title: "こでおｗみねヴぁろおめこｄ",
      thumbnail: "https://img.youtube.com/vi/bNYh7r7j4Tc/maxresdefault.jpg",
      tags: ["codeName", "overwatch2", "Minecraft", "VALORANT", "omegaStrikers", "MW2"],
      uploadDate: "2023-07-01",
      duration: "3:15",
      videoId: "bNYh7r7j4Tc",
      description: "Code Name、Overwatch2、Minecraft、VALORANT、Omega Strikers、MW2の夏動画。",
    },
    {
      id: "32",
      title: "え、こんなのもわかんないの？",
      thumbnail: "https://img.youtube.com/vi/go1Ef1ycFGc/maxresdefault.jpg",
      tags: ["BananaShooter", "overwatch2", "Minecraft", "漢字でGO!", "VALORANT"],
      uploadDate: "2023-08-01",
      duration: "7:28",
      videoId: "go1Ef1ycFGc",
      description: "Banana Shooter、Overwatch2、Minecraft、漢字でGO!、VALORANTでの夏休み動画。",
    },
    {
      id: "33",
      title: "おれキルジョイウルト壊せるよ",
      thumbnail: "https://img.youtube.com/vi/JRdsDYwx_C4/hqdefault.jpg",
      tags: ["overwatch2", "MW2", "omegaStrikers", "VALORANT"],
      uploadDate: "2023-09-01",
      duration: "5:04",
      videoId: "JRdsDYwx_C4",
      description: "Overwatch2、MW2、Omega Strikers、VALORANTでの秋の企画動画。",
    },
    {
      id: "34",
      title: "第二ラウンド、開始！",
      thumbnail: "https://img.youtube.com/vi/B3Xm_Gg6tyA/maxresdefault.jpg",
      tags: ["MW2", "CS2", "VALORANT", "omegaStrikers", "雀魂", "Fallguys"],
      uploadDate: "2023-10-01",
      duration: "7:43",
      videoId: "B3Xm_Gg6tyA",
      description: "MW2、CS2、VALORANT、Omega Strikers、雀魂、Fall Guysでのハロウィン動画。",
    },
    {
      id: "35",
      title: 'おれ""ら""と、勝負だ！',
      thumbnail: "https://img.youtube.com/vi/sE8ChFlibUY/hqdefault.jpg",
      tags: ["MW2", "overwatch2", "VALORANT", "omegaStrikers"],
      uploadDate: "2023-11-01",
      duration: "4:34",
      videoId: "sE8ChFlibUY",
      description: "MW2、Overwatch2、VALORANT、Omega Strikersでの年末に向けた動画。",
    },
    {
      id: "36",
      title: "ホウカイ・シティ",
      thumbnail: "https://img.youtube.com/vi/-gbYijNlQrU/hqdefault.jpg",
      tags: ["MW3", "overwatch2", "VALORANT", "omegaStrikers", "HonkaiStarRail"],
      uploadDate: "2023-12-01",
      duration: "4:54",
      videoId: "-gbYijNlQrU",
      description: "MW3、Overwatch2、VALORANT、Omega Strikers、Honkai Star Railでの2023年最後の動画。",
    },
  ],
  "2022": [
    {
      id: "37",
      title: "ヴァロナッツモール",
      thumbnail: "https://img.youtube.com/vi/ZRlnJZRxUXI/maxresdefault.jpg",
      tags: ["VALORANT"],
      uploadDate: "2022-04-01",
      duration: "2:33",
      videoId: "ZRlnJZRxUXI",
      description: "VALORANTでの月一更新開始記念の第一回動画です。",
    },
    {
      id: "38",
      title: "あし笛の鶏",
      thumbnail: "https://img.youtube.com/vi/rp4HfOIu9Cg/hqdefault.jpg",
      tags: ["Minecraft", "overwatch", "VALORANT"],
      uploadDate: "2022-05-01",
      duration: "2:53",
      videoId: "rp4HfOIu9Cg",
      description: "Minecraft、Overwatch、VALORANTでの月一更新2回目の動画。",
    },
    {
      id: "39",
      title: "NI-CE! disco",
      thumbnail: "https://img.youtube.com/vi/HN2wU0IKe68/hqdefault.jpg",
      tags: ["VALORANT", "overwatch"],
      uploadDate: "2022-06-01",
      duration: "3:01",
      videoId: "HN2wU0IKe68",
      description: "VALORANTとOverwatchでの3回目の投稿動画。",
    },
    {
      id: "40",
      title: "やる気switch",
      thumbnail: "https://img.youtube.com/vi/gq8t_WgtBi8/hqdefault.jpg",
      tags: ["Fallguys", "TheCycleFrontier", "overwatch", "VALORANT"],
      uploadDate: "2022-07-01",
      duration: "3:15",
      videoId: "gq8t_WgtBi8",
      description: "Fall Guys、The Cycle Frontier、Overwatch、VALORANTでの夏の動画。",
    },
    {
      id: "41",
      title: "サケビ・ソウオン・ヴァロラントーズ",
      thumbnail: "https://img.youtube.com/vi/iJwG0lsXGT8/maxresdefault.jpg",
      tags: ["Minecraft", "VALORANT", "雀魂"],
      uploadDate: "2022-08-01",
      duration: "3:26",
      videoId: "iJwG0lsXGT8",
      description: "Minecraft、VALORANT、雀魂での夏休み期間中の動画。",
    },
    {
      id: "42",
      title: "butterflying in the 90's",
      thumbnail: "https://img.youtube.com/vi/jswORyEn5jE/hqdefault.jpg",
      tags: ["GUNDAM EVOLUTION", "VALORANT"],
      uploadDate: "2022-09-01",
      duration: "2:39",
      videoId: "jswORyEn5jE",
      description: "GUNDAM EVOLUTION、VALORANTでの月一更新半年記念動画。",
    },
    {
      id: "43",
      title: "なにわの鶏",
      thumbnail: "https://img.youtube.com/vi/5lufhJQzme4/hqdefault.jpg",
      tags: ["overwatch2", "VALORANT"],
      uploadDate: "2022-10-01",
      duration: "5:31",
      videoId: "5lufhJQzme4",
      description: "Overwatch2、VALORANTでの秋の新ゲーム挑戦動画。",
    },
    {
      id: "44",
      title: "真白の鶏、出撃！",
      thumbnail: "https://img.youtube.com/vi/L9u7NTEn0FQ/hqdefault.jpg",
      tags: ["Phasmophobia", "VALORANT", "overwatch2"],
      uploadDate: "2022-11-01",
      duration: "8:51",
      videoId: "L9u7NTEn0FQ",
      description: "Phasmophobia、VALORANT、Overwatch2での年末に向けた動画。",
    },
    {
      id: "45",
      title: "あずうオドル",
      thumbnail: "https://img.youtube.com/vi/L4esLdnr0z0/maxresdefault.jpg",
      tags: ["overwatch2", "VALORANT"],
      uploadDate: "2022-12-01",
      duration: "4:26",
      videoId: "L4esLdnr0z0",
      description: "Overwatch2、VALORANTでの月一更新初年末動画。",
    },
  ],
}

export function findVideoById(id: string): Video | undefined {
  for (const yearVideos of Object.values(videosByYear)) {
    const video = yearVideos.find((v) => v.id === id)
    if (video) return video
  }
  return undefined
}
